name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Angular project
      run: npm run build --prod 

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        eval $(ssh-agent -s)
        ssh-add private_key
    - name: Deploy to Server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: rsync -avz -e "ssh -vvv -o StrictHostKeyChecking=no" dist/project-cargo/browser/ $USER@$HOST:$REMOTE_PATH

